#ifndef BMP_INFO_H_INCLUDED
#define BMP_INFO_H_INCLUDED

#define PIXEL_MAX_VAL 255

#define OFFSET_START_POS 10
#define OFFSET_END_POS 13
#define OFFSET_INFO_LENGTH (OFFSET_END_POS-OFFSET_START_POS)+1

#define WIDTH_START_POS 18
#define WIDTH_END_POS 21
#define WIDTH_INFO_LENGTH (WIDTH_END_POS-WIDTH_START_POS)+1

#define HEIGHT_START_POS 22
#define HEIGHT_END_POS 25
#define HEIGHT_INFO_LENGTH (HEIGHT_END_POS-HEIGHT_START_POS)+1

#define DEPTH_START_POS 28
#define DEPTH_END_POS 29
#define DEPTH_INFO_LENGTH (DEPTH_END_POS-DEPTH_START_POS)+1

#define PADDING_FACTOR 4

#endif // BMP_INFO_H_INCLUDED
