#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define WRONG_CMD_ARGS_FORMAT 1
#define INPUT_PATH_DOES_NOT_EXIST 2
#define PGM_BMP_OUTPUT_PATHS_EXIST 3
#define COULD_NOT_OPEN_FILE 4
#define UNSUPPORTED_BIT_DEPTH 5

#endif